"""Stage-by-stage candidate-recall harness for the evidence tagger.

WHY THIS EXISTS
---------------
The tagger's recall failures live at DIFFERENT pipeline stages, and a single
final-tag number can't tell them apart. A control the doc should tag to can be
lost because:

  * GENERATION  — no lane ever nominated it (terse enhancement text, vocab
                  mismatch like "multi-factor" vs "multifactor").
  * FUSION+CAP  — a lane DID nominate it, but RRF ranked it past _RAG_FUSED_CAP
                  and it was truncated before the judge saw it.
  * JUDGE       — it reached the judge but was scored < accept threshold.

This harness runs the REAL tagger internals against a REAL evidence corpus and
reports recall at each stage, measured against a ground-truth control set (the
known-good Claude baseline). Every candidate-generation fix (folder-truncation,
char n-grams, must-judge cap-exemption, enhancement expansion, parent-aware
retrieval, section-level retrieval) gets a before/after number here so we can
prove recall went UP and precision did NOT go down — instead of guessing.

It is a MEASUREMENT TOOL, not a CI gate (mirrors score_recall.py /
scripts/eval_workbook.py). No LLM judge is invoked by default (the generation
and cap stages are LLM-free and deterministic given a fixed HyDE prose); pass
--with-judge to also measure the judged stage against a live client.

GROUND TRUTH
------------
``--truth-db`` points at a completed assessor.sqlite whose evidencetag rows are
treated as the oracle: for each evidence title, the set of distinct control_ids
it was tagged to. The default is the Claude baseline in the recycle bin. The
harness re-runs candidate generation for the SAME documents (matched by title →
on-disk file under --evidence-root) and reports, per doc and micro-averaged:

    truth              controls the baseline tagged (oracle)
    gen_recall         fraction of truth generated by ANY lane (generation ceiling)
    cap_recall         fraction of truth surviving the RRF top-15 cap
    (judge_recall)     fraction of truth the judge accepts   [--with-judge]

USAGE
-----
    cd backend
    uv run --no-sync python scripts/stage_recall_harness.py \
        --evidence-root "C:/.../eMASS_BoE_Upload+Stigs_07112026" \
        --framework-id 2 \
        [--truth-db "C:/$Recycle.Bin/.../assessor.sqlite"] \
        [--catalog-db ~/.cybersecurity-assessor/assessor.sqlite] \
        [--with-judge] [--json out.json] [--only-broad N]

Deterministic stages (gen/cap) need no network. --with-judge and the HyDE lane
need a live OpenAI client (resolved from config), matching production.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sqlite3
import statistics
import sys
import tempfile
import zipfile
from pathlib import Path
from typing import Any

_BACKEND = Path(__file__).resolve().parents[1]
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

from sqlmodel import Session, create_engine, select  # noqa: E402

from cybersecurity_assessor import config as cfg  # noqa: E402
from cybersecurity_assessor import models  # noqa: F401,E402 -- register tables
from cybersecurity_assessor.evidence import tagger as T  # noqa: E402
from cybersecurity_assessor.models import Control  # noqa: E402

# Recycle-bin Claude baseline (the good run) — override with --truth-db.
_DEFAULT_TRUTH = (
    r"C:/$Recycle.Bin/S-1-5-21-1537797257-1354249956-583321750-298009/"
    r"$R8PG9EC.cybersecurity-assessor/assessor.sqlite"
)


# ---------------------------------------------------------------------------
# Ground truth: title -> {control_id lower} from a completed assessor DB
# ---------------------------------------------------------------------------
def load_truth(truth_db: str) -> dict[str, set[str]]:
    con = sqlite3.connect(f"file:{truth_db}?mode=ro", uri=True)
    truth: dict[str, set[str]] = {}
    q = """
        select e.title, c.control_id
        from evidencetag t
        join evidence e on e.id = t.evidence_id
        join objective o on o.id = t.objective_id
        join control c on c.id = o.control_id_fk
        group by e.title, c.control_id
    """
    for title, cid in con.execute(q):
        if title:
            truth.setdefault(title, set()).add(cid.lower())
    con.close()
    return truth


# ---------------------------------------------------------------------------
# Catalog (cids + control_texts) — built with the SAME production functions the
# tagger uses (_all_objectives_by_control + _control_reference_text +
# _augment_control_text), so the harness scores against the IDENTICAL retrieval
# corpus production does. Also returns all_by_control for the folder lane.
# ---------------------------------------------------------------------------
def load_catalog(
    catalog_db: str, framework_id: int, augment: bool = True
) -> tuple[list[str], list[str], dict]:
    tmp = tempfile.mkdtemp(prefix="harness_cat_")
    dst = os.path.join(tmp, "cat.sqlite")
    sc = sqlite3.connect(f"file:{catalog_db}?mode=ro", uri=True)
    dc = sqlite3.connect(dst)
    sc.backup(dc)
    dc.close()
    sc.close()
    eng = create_engine(f"sqlite:///{dst}", connect_args={"check_same_thread": False})
    with Session(eng) as s:
        all_by_control = T._all_objectives_by_control(s, framework_id=framework_id)
        control_by_cid = T._controls_by_cid(s, framework_id=framework_id)
    eng.dispose()
    cids = sorted(all_by_control.keys())
    # EXACTLY mirror tagger._tag_via_llm's RETRIEVAL corpus build (the split:
    # _retrieval_reference_text = title+statement+objective, ODP-stripped, +gloss).
    # This is candidate-generation text; the judge uses clean normative text
    # separately (not exercised by the generation/cap stages measured here).
    if augment:
        control_texts = [
            T._augment_control_text(
                cid,
                T._retrieval_reference_text(control_by_cid.get(cid), all_by_control[cid]),
            )
            for cid in cids
        ]
    else:
        control_texts = [
            T._retrieval_reference_text(control_by_cid.get(cid), all_by_control[cid])
            for cid in cids
        ]
    return cids, control_texts, all_by_control


# ---------------------------------------------------------------------------
# Evidence file resolution (title -> on-disk docx/pdf) + text extraction
# ---------------------------------------------------------------------------
def _norm(x: str) -> str:
    return re.sub(r"[^a-z0-9]", "", x.lower())


def index_evidence_files(root: str) -> list[str]:
    return [
        f
        for f in glob.glob(root + "/**/*", recursive=True)
        if f.lower().endswith((".docx", ".pdf"))
    ]


def find_file(title: str, files: list[str]) -> str | None:
    """Collision-SAFE title->file match. Returns a file only when EXACTLY ONE
    candidate matches; ambiguous (>1) or no match returns None (skipped, not
    silently scored against the wrong doc).

    Truth-DB titles are stored TRUNCATED to 40 chars (title[:40]), which cuts
    long BoE names mid-word (e.g. "..._Account_Manageme") so neither string
    contains the other AND a fixed 16-char prefix can collide across sibling
    USD-numbered docs. So the match is: (a) full containment either way, OR
    (b) a LONG shared normalized prefix (>=24 chars) — long enough that the
    USD number + several title words align, short enough to survive the 40-char
    truncation. Collision safety is preserved by the exactly-one-hit rule."""
    # Strip the eMASS "NN.x.XX_" ordering prefix from BOTH sides — the truth-DB
    # title often carries it (01.o.AC_USD...) while the filename does too; if we
    # only strip the filename the normalized prefixes never align.
    _pfx = re.compile(r"^\d+\.[a-z]\.[A-Za-z]{2}_")
    tn = _norm(_pfx.sub("", title))
    hits: list[str] = []
    for f in files:
        stem = _pfx.sub("", os.path.splitext(os.path.basename(f))[0])
        sn = _norm(stem)
        if not sn:
            continue
        # longest common prefix length
        lcp = 0
        for a, b in zip(tn, sn):
            if a != b:
                break
            lcp += 1
        if (
            (len(sn) >= 8 and sn in tn)
            or (len(tn) >= 8 and tn in sn)
            or lcp >= 24
        ):
            hits.append(f)
    if len(hits) == 1:
        return hits[0]
    return None  # 0 or ambiguous -> skip (never guess)


def read_text(f: str) -> str:
    """Extract text via the app's OWN extractor so the harness sees exactly what
    the tagger sees (pdfplumber/pypdf for PDF, python-docx for docx). Falls back
    to a raw docx-xml strip if the extractor errors."""
    try:
        from cybersecurity_assessor.evidence.extractors import extract_stream

        with open(f, "rb") as stream:
            doc = extract_stream(stream, os.path.basename(f))
        return (doc.text or "").strip()
    except Exception:
        if f.lower().endswith(".docx"):
            try:
                with zipfile.ZipFile(f) as z:
                    xml = z.read("word/document.xml").decode("utf-8", "ignore")
                return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", xml)).strip()
            except Exception:
                return ""
        return ""


# ---------------------------------------------------------------------------
# Stage runners — replicate _generate_candidates faithfully but expose stages
# ---------------------------------------------------------------------------
_LANE_NAMES = ("sparse", "hyde", "dense", "dense_sections", "triage", "folder")


def _folder_lane_variant(
    path: str | None,
    all_by_control: dict,
    cids: list[str],
    control_texts: list[str],
    doc_text: str,
    mode: str,
) -> list[str]:
    """Folder lane under one of three ORDERING policies, so the harness can
    measure them head-to-head on the identical corpus (the only rigorous test):

      alpha      OLD behavior — sorted() on the string cid, top-N. Indefensible:
                 ia-2.10 sorts before ia-2.2, drops ia-2.8 at position ~16.
      numeric    sort by (family, base#, enh#), base first. Correct ID order but
                 still an ID prior with ZERO relevance signal — just changes
                 WHICH arbitrary 15 survive (measured net-zero).
      relevance  rank family members by TF-IDF cosine of the DOCUMENT against
                 each control's text (the same _tier3 scorer the sparse lane
                 uses), keep top-N. A real within-family relevance prior — keeps
                 the 15 most-relevant IA controls, not the 15 lowest-numbered.
                 This is the IR-defensible fix (per review): truncate a recall
                 lane by relevance, never by identifier.
    """
    fam = T._family_from_path(path)
    if not fam:
        return []
    fam_cids = [c for c in all_by_control if c.split("-", 1)[0] == fam]
    if mode == "alpha":
        return sorted(fam_cids)[: T._RAG_PER_LANE_TOPN]
    if mode == "numeric":
        return sorted(fam_cids, key=T._cid_numeric_key)[: T._RAG_PER_LANE_TOPN]
    # relevance: score each family control's text vs the document body.
    text_by_cid = dict(zip(cids, control_texts))
    fam_texts = [text_by_cid.get(c, "") for c in fam_cids]
    scores = T._tier3_relevance_scores(doc_text, fam_texts)
    ranked = sorted(zip(fam_cids, scores), key=lambda t: (-t[1], T._cid_numeric_key(t[0])))
    return [c for c, _ in ranked][: T._RAG_PER_LANE_TOPN]


def stage_candidates(
    text: str,
    hyde: str,
    cids: list[str],
    control_texts: list[str],
    all_by_control: dict,
    evidence_path: str,
    framework_id: int,
    folder_rank: str = "numeric",
    section_lane: bool = True,
    cap: int | None = None,
) -> dict[str, Any]:
    """Run the SAME lane+RRF+cap logic as tagger._generate_candidates and return
    a full LEDGER for the document, so selector experiments (folder ordering,
    RRF, caps, quotas, must-judge policies) can be replayed OFFLINE without any
    LLM calls.

    Ledger keys:
      lanes       {lane_name: [cid,...]}      untruncated per-lane output+rank
      rrf         {cid: fused_score}          summed RRF contribution
      generated   set[cid]                    union of all lanes (generation set)
      capped      [cid,...]                    survivors of the top-_RAG_FUSED_CAP

    Uses the REAL all_by_control and REAL evidence_path so the folder lane keys
    off the eMASS NN.XX folder token exactly as production does. Omits only the
    tool_candidate_cids injection (which would ADD candidates) — documented as a
    faithful LOWER BOUND on production candidate recall.

    ``folder_rank`` selects the folder lane ordering policy (alpha|numeric|
    relevance) so the harness can measure all three on the identical corpus."""
    valid = {c for c in cids}
    folder = _folder_lane_variant(
        evidence_path, all_by_control, cids, control_texts, text, folder_rank
    )
    lane_out: dict[str, list[str]] = {
        "sparse": T._lane_sparse(text, cids, control_texts),
        "hyde": T._lane_hyde(hyde, cids, control_texts),
        "dense": T._lane_dense(text, cids, control_texts, framework_id=framework_id),
        "triage": T._lane_triage(hyde, valid),
        "folder": folder,
    }
    # Section-max-pool dense lane is toggleable so before/after (5-lane vs 6-lane)
    # runs on the IDENTICAL harness — the only rigorous way to measure its delta.
    if section_lane:
        lane_out["dense_sections"] = T._lane_dense_sections(
            text, cids, control_texts, framework_id=framework_id
        )
    all_generated: set[str] = set()
    for lane in lane_out.values():
        all_generated.update(lane)
    fused: dict[str, float] = {}
    for lane in lane_out.values():
        for cid, contrib in T._rank_to_rrf(lane).items():
            fused[cid] = fused.get(cid, 0.0) + contrib
    ranked = sorted(fused.items(), key=lambda kv: (-kv[1], kv[0]))
    # cap override: None -> production _RAG_FUSED_CAP; a huge value -> "uncapped"
    # (judge every generated candidate, bounded by the ~52/doc generation ceiling).
    eff_cap = T._RAG_FUSED_CAP if cap is None else cap
    capped = [cid for cid, _ in ranked[:eff_cap]]
    return {
        "lanes": lane_out,
        "rrf": fused,
        "generated": all_generated,
        "capped": capped,
    }


def _is_enhancement(cid: str) -> bool:
    """True for a NIST enhancement id (has a dotted-decimal suffix, e.g. ia-2.8)."""
    _, _, rest = cid.partition("-")
    return "." in rest


def judge_scores(
    client: Any,
    judge_model: str,
    doc_text: str,
    title: str,
    candidates: list[str],
    all_by_control: dict,
) -> dict[str, float]:
    """Run the REAL strict judge (same brief + per-candidate user text as
    tagger._tag_via_llm) over ``candidates`` and return {cid: score}.

    Returns raw scores (not the 0.6-gated accept set) so the caller can slice
    accept/precision/recall at MULTIPLE cap sizes from a single judged pass —
    judging the full generated set ONCE answers the whole 15/30/50/uncapped
    curve instead of paying a separate judged run per cap. Uses the CLEAN
    normative judge text (_control_reference_text), exactly like production.
    A stuck/failed call is omitted (treated as not-scored → not accepted)."""
    if not candidates:
        return {}
    brief = T._build_llm_brief(title, T._llm_artifact_body(doc_text))
    scores: dict[str, float] = {}

    def _one(cid: str) -> tuple[str, float | None]:
        ref = T._control_reference_text(all_by_control.get(cid, []))
        user_text = T._llm_candidate_user_text(cid, ref)
        score, _reasoning, _usage = client.judge_relevance(
            brief, user_text, model=judge_model
        )
        return cid, score

    # Bounded parallelism + HARD per-future wall-clock so one wedged gateway call
    # can't freeze the run (it once hung for days). Concurrency 5 = gd-ms safe limit.
    from concurrent.futures import ThreadPoolExecutor, TimeoutError as _FTimeout
    from concurrent.futures import as_completed

    with ThreadPoolExecutor(max_workers=5, thread_name_prefix="harness-judge") as pool:
        futs = {pool.submit(_one, cid): cid for cid in candidates}
        for fut in as_completed(futs, timeout=180 + 15 * len(candidates)):
            try:
                cid, score = fut.result(timeout=60)
            except (_FTimeout, Exception):  # noqa: BLE001 — stuck/failed = unscored
                continue
            if score is not None and score >= 0.0:
                scores[cid] = score
    return scores


def _catalog_version(cids: list[str], control_texts: list[str]) -> str:
    """Stable digest of the ALREADY-LOADED catalog corpus (cids + retrieval
    text) so a ledger/cache entry is invalidated when the catalog changes.
    Content-based, not mtime → reproducible across machines. Takes the loaded
    corpus (NOT the db path) so the harness never pays a second full
    load_catalog (backup + re-embed) just to compute the version."""
    import hashlib

    blob = "\x1e".join(f"{c}\x1f{t}" for c, t in zip(cids, control_texts))
    return hashlib.sha1(blob.encode("utf-8", "replace")).hexdigest()[:12]


def _code_version() -> str:
    """Digest of the tagger source so ledger runs are attributable to code."""
    import hashlib

    src = Path(T.__file__).read_bytes()
    return hashlib.sha1(src).hexdigest()[:12]


def _hyde_cache_key(model: str, prompt_ver: str, text: str) -> str:
    """Content-addressed HyDE cache key. Includes MODEL and the HyDE framing
    PROMPT version (scaffold set) alongside the doc content, so switching model
    or editing the scaffolds invalidates stale prose instead of silently reusing
    a mismatched expansion (a correctness trap the critique flagged)."""
    import hashlib

    payload = f"{model}\x1e{prompt_ver}\x1e{text}"
    return hashlib.sha256(payload.encode("utf-8", "replace")).hexdigest()[:16]


def _hyde_prompt_version() -> str:
    """Digest of the HyDE scaffold set so prompt edits bust the cache."""
    import hashlib

    from cybersecurity_assessor.llm import client as _lc

    scaffolds = getattr(_lc, "_HYDE_SCAFFOLDS", None)
    blob = "\x1e".join(scaffolds) if scaffolds else "unknown"
    return hashlib.sha1(blob.encode("utf-8", "replace")).hexdigest()[:8]


def _install_production_tls() -> None:
    """Use the OS-native trust store exactly as the production sidecar does
    (cybersecurity_assessor.tls.install → truststore.inject_into_ssl), so the
    harness verifies TLS against the SAME corporate CA the app uses. NO
    verify=False anywhere — a TLS failure here is a real, fatal signal, not
    something to paper over on evidence data."""
    from cybersecurity_assessor import tls

    tls.install()


def _assert_doc_invariants(
    tset: set[str],
    catalog_ids: set[str],
    ledger: dict[str, Any],
    ungenerated: list[str],
    capped_out: list[str],
    gen_recall: float,
    cap_recall: float,
) -> None:
    """Hard, mathematically self-checking invariants (per the critique). If any
    fail the harness ABORTS — a silent metric discrepancy must never survive.
    Truth is scoped to the CURRENT catalog first (a truth id absent from the
    catalog can't be generated and is reported separately, not counted as a
    generation miss)."""
    truth_in_cat = tset & catalog_ids
    generated = ledger["generated"]
    selected = set(ledger["capped"])
    generated_truth = truth_in_cat & generated
    selected_truth = truth_in_cat & selected

    assert set(ungenerated) == truth_in_cat - generated, (
        f"ungenerated mismatch: {set(ungenerated)} != {truth_in_cat - generated}"
    )
    assert set(capped_out) == generated_truth - selected, (
        f"capped_out mismatch: {set(capped_out)} != {generated_truth - selected}"
    )
    if truth_in_cat:
        assert abs(gen_recall - len(generated_truth) / len(truth_in_cat)) < 1e-9
        assert abs(cap_recall - len(selected_truth) / len(truth_in_cat)) < 1e-9
    # selected is always a subset of generated (can't survive a cap un-generated)
    assert selected_truth <= generated_truth


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--evidence-root", required=True)
    ap.add_argument("--framework-id", type=int, default=2)
    ap.add_argument("--truth-db", default=_DEFAULT_TRUTH)
    ap.add_argument(
        "--catalog-db",
        default=os.path.join(
            os.path.expanduser("~"), ".cybersecurity-assessor", "assessor.sqlite"
        ),
    )
    ap.add_argument("--model", default="gpt-5.6-sol")
    ap.add_argument("--only-broad", type=int, default=0,
                    help="only docs whose truth set exceeds this many controls")
    ap.add_argument("--json", default="")
    ap.add_argument("--ledger", default="",
                    help="write the full replayable candidate ledger to this path")
    ap.add_argument("--folder-rank", choices=["alpha", "numeric", "relevance"],
                    default="numeric",
                    help="folder lane ordering policy to measure (default numeric)")
    ap.add_argument("--no-section-lane", action="store_true",
                    help="disable the section-max-pool dense lane (measure 5-lane before state)")
    ap.add_argument("--cap", type=int, default=0,
                    help="override fused cap size (0=production _RAG_FUSED_CAP; "
                         "9999=effectively uncapped)")
    ap.add_argument("--with-judge", action="store_true",
                    help="PRECISION GATE: run the real judge on capped candidates; "
                         "report precision-after-judging, recall-after-judge, and "
                         "judge-call count (costs LLM calls, ~15/doc)")
    ap.add_argument("--judge-model", default="",
                    help="judge model (default: --model)")
    args = ap.parse_args()

    # Production-faithful TLS: OS trust store, no verify=False. Fatal if the
    # gateway is unreachable — better a loud failure than understated recall.
    _install_production_tls()

    truth = load_truth(args.truth_db)
    cids, control_texts, all_by_control = load_catalog(
        args.catalog_db, args.framework_id
    )
    catalog_ids = set(cids)
    files = index_evidence_files(args.evidence_root)

    import httpx
    from openai import OpenAI

    from cybersecurity_assessor.engine import narrative_embeddings as _ne
    from cybersecurity_assessor.llm.client import OpenAIClient

    base, tok = cfg.resolve_openai_endpoint()
    # Normal clients — TLS verified via the OS trust store patched above.
    sdk = OpenAI(base_url=base, api_key=tok, max_retries=1, timeout=60)
    client = OpenAIClient(model=args.model, _sdk_client=sdk)

    # Dense lane must be LIVE and production-faithful. Build a normal embeddings
    # provider (verified TLS) and pin resolve_provider to it. FATAL if the probe
    # fails — a dead dense lane silently understates recall, so we refuse to
    # produce numbers rather than emit misleading ones.
    _emb_sdk = OpenAI(base_url=base, api_key=tok, max_retries=1, timeout=30)
    _emb_provider = _ne.OpenAIEmbeddingsProvider(_sdk_client=_emb_sdk)
    _probe = _emb_provider.embed(["multifactor authentication probe"])
    if not (_probe and _probe[0]):
        raise SystemExit("FATAL: embeddings probe returned empty — dense lane dead.")
    print(
        f"[dense lane LIVE] dim={len(_probe[0])} model={_emb_provider.model_name} "
        f"(TLS via OS trust store)"
    )
    _ne.resolve_provider = lambda *a, **k: _emb_provider  # type: ignore[assignment]

    # Immutable run metadata — every ledger/result is attributable to exactly
    # which model, prompt, catalog, and code produced it.
    prompt_ver = _hyde_prompt_version()
    meta = {
        "model": args.model,
        "hyde_prompt_version": prompt_ver,
        "catalog_version": _catalog_version(cids, control_texts),
        "code_version": _code_version(),
        "framework_id": args.framework_id,
        "rag_fused_cap": T._RAG_FUSED_CAP,
        "per_lane_topn": T._RAG_PER_LANE_TOPN,
    }
    print(f"[run] {meta}")

    docs = {t: cs for t, cs in truth.items() if len(cs) > args.only_broad}
    per_doc: list[dict[str, Any]] = []
    ledger_docs: list[dict[str, Any]] = []
    gen_r: list[float] = []
    cap_r: list[float] = []
    # micro accumulators (association-level, per the critique)
    micro_truth = micro_gen = micro_sel = 0
    micro_enh_truth = micro_enh_gen = micro_enh_sel = 0
    truth_absent: dict[str, list[str]] = {}
    # precision-gate accumulators (--with-judge): judged = accepted-by-judge
    j_accepted = j_accepted_truth = j_calls = 0
    judge_model = args.judge_model or args.model

    cache_dir = Path(__file__).resolve().parent / "_hyde_cache"
    cache_dir.mkdir(exist_ok=True)

    for title, tset in sorted(docs.items(), key=lambda kv: -len(kv[1])):
        f = find_file(title, files)
        if not f:
            continue
        text = read_text(f)
        if not text:
            continue
        # Content-addressed HyDE cache (model + prompt-version + content).
        key = _hyde_cache_key(args.model, prompt_ver, text)
        cf = cache_dir / f"{key}.txt"
        # One-time migration: earlier runs keyed on (model + content) WITHOUT the
        # prompt version. If a legacy file exists for this doc, re-key it to the
        # new format rather than paying ~125s to regenerate identical prose.
        if not cf.exists():
            import hashlib as _hl
            legacy = cache_dir / (
                _hl.sha256((args.model + "\x1e" + text).encode("utf-8", "replace"))
                .hexdigest()[:16] + ".txt"
            )
            if legacy.exists():
                cf.write_text(legacy.read_text(encoding="utf-8"), encoding="utf-8")
        if cf.exists():
            hyde = cf.read_text(encoding="utf-8")
        else:
            hyde = client.expand_to_control_prose_multi(text)
            cf.write_text(hyde, encoding="utf-8")

        ev_path = "file:///" + f.replace("\\", "/")
        ledger = stage_candidates(
            text, hyde, cids, control_texts, all_by_control, ev_path,
            args.framework_id, folder_rank=args.folder_rank,
            section_lane=not args.no_section_lane,
            cap=(args.cap or None),
        )

        # Scope truth to the catalog FIRST; report absent ids separately.
        truth_in_cat = tset & catalog_ids
        absent = sorted(tset - catalog_ids)
        if absent:
            truth_absent[title[:40]] = absent
        if not truth_in_cat:
            continue

        generated = ledger["generated"]
        selected = set(ledger["capped"])
        generated_truth = truth_in_cat & generated
        selected_truth = truth_in_cat & selected
        g = len(generated_truth) / len(truth_in_cat)
        c = len(selected_truth) / len(truth_in_cat)
        ungenerated = sorted(truth_in_cat - generated)
        capped_out = sorted(generated_truth - selected)

        # HARD self-check — abort on any inconsistency.
        _assert_doc_invariants(
            tset, catalog_ids, ledger, ungenerated, capped_out, g, c
        )

        gen_r.append(g)
        cap_r.append(c)
        micro_truth += len(truth_in_cat)
        micro_gen += len(generated_truth)
        micro_sel += len(selected_truth)
        enh_truth = {x for x in truth_in_cat if _is_enhancement(x)}
        micro_enh_truth += len(enh_truth)
        micro_enh_gen += len(enh_truth & generated)
        micro_enh_sel += len(enh_truth & selected)

        # PRECISION GATE: judge the FULL generated set (RRF-ranked), record raw
        # scores. Judging everything once lets the summary slice accept/precision/
        # recall at ANY cap size (15/30/50/uncapped) from this single pass.
        doc_judge: dict[str, Any] = {}
        if args.with_judge:
            ranked_all = [
                cid for cid, _ in sorted(
                    ledger["rrf"].items(), key=lambda kv: (-kv[1], kv[0])
                )
            ]
            sc = judge_scores(
                client, judge_model, text, title, ranked_all, all_by_control
            )
            accepted = {c for c, s in sc.items() if s >= T._LLM_TIER_ACCEPT_SCORE}
            acc_truth = accepted & truth_in_cat
            j_accepted += len(accepted)
            j_accepted_truth += len(acc_truth)
            j_calls += len(sc)
            doc_judge = {
                "judge_calls": len(sc),
                "ranked_all": ranked_all,          # RRF order (for cap slicing)
                "truth_in_cat": sorted(truth_in_cat),  # exact doc truth (curve)
                "scores": {c: round(s, 3) for c, s in sc.items()},
                "accepted": sorted(accepted),
                "accepted_truth": sorted(acc_truth),
                "false_accepts": sorted(accepted - truth_in_cat),
                "precision": round(len(acc_truth) / len(accepted), 3) if accepted else None,
                "recall_after_judge": round(len(acc_truth) / len(truth_in_cat), 3),
            }

        # Per-lane truth coverage (which lane nominated each truth control).
        lane_hits = {
            ln: sorted(truth_in_cat & set(cs)) for ln, cs in ledger["lanes"].items()
        }
        per_doc.append({
            "title": title[:40],
            "truth": len(truth_in_cat),
            "truth_absent_from_catalog": absent,
            "gen_recall": round(g, 3),
            "cap_recall": round(c, 3),
            "ungenerated": ungenerated,
            "capped_out": capped_out,
            "lane_truth_hits": lane_hits,
            **({"judge": doc_judge} if doc_judge else {}),
        })
        if args.ledger:
            ledger_docs.append({
                "title": title,
                "hyde_key": key,
                "truth": sorted(tset),
                "truth_in_catalog": sorted(truth_in_cat),
                "lanes": ledger["lanes"],           # untruncated per-lane rank
                "rrf": {k: round(v, 6) for k, v in ledger["rrf"].items()},
                "generated": sorted(generated),
                "capped": ledger["capped"],         # post-cap, in rank order
            })
        print(
            f"{title[:34]:34} truth={len(truth_in_cat):2} "
            f"gen={g:.0%} cap={c:.0%} "
            f"| ungen={ungenerated} capped_out={capped_out}"
        )

    if not gen_r:
        print("No matched docs — check --evidence-root / title matching.")
        return 0

    macro_gen = statistics.mean(gen_r)
    macro_cap = statistics.mean(cap_r)
    micro_gen_r = micro_gen / micro_truth if micro_truth else 0.0
    micro_cap_r = micro_sel / micro_truth if micro_truth else 0.0
    enh_gen_r = micro_enh_gen / micro_enh_truth if micro_enh_truth else None
    enh_cap_r = micro_enh_sel / micro_enh_truth if micro_enh_truth else None
    broad = [d for d in per_doc if d["truth"] >= 6]
    broad_gen = statistics.mean([d["gen_recall"] for d in broad]) if broad else None
    broad_cap = statistics.mean([d["cap_recall"] for d in broad]) if broad else None

    print(f"\nn={len(gen_r)} docs, {micro_truth} truth associations in-catalog")
    print(f"  MACRO  gen={macro_gen:.1%}  cap={macro_cap:.1%}   (per-doc average)")
    print(f"  MICRO  gen={micro_gen_r:.1%}  cap={micro_cap_r:.1%}   "
          f"(association-level: {micro_gen}/{micro_truth} gen, "
          f"{micro_sel}/{micro_truth} post-cap)")
    if enh_gen_r is not None:
        print(f"  ENH    gen={enh_gen_r:.1%}  cap={enh_cap_r:.1%}   "
              f"(enhancements only: {micro_enh_sel}/{micro_enh_truth} post-cap)")
    if broad_gen is not None:
        print(f"  BROAD  gen={broad_gen:.1%}  cap={broad_cap:.1%}   "
              f"(docs with >=6 truth: n={len(broad)})")
    # PRECISION GATE summary (only with --with-judge).
    judge_precision = judge_recall = None
    if args.with_judge and micro_truth:
        judge_precision = j_accepted_truth / j_accepted if j_accepted else None
        judge_recall = j_accepted_truth / micro_truth
        pstr = f"{judge_precision:.1%}" if judge_precision is not None else "n/a"
        print(f"  JUDGE  precision={pstr}  recall_after_judge={judge_recall:.1%}   "
              f"(accepted {j_accepted_truth} truth of {j_accepted} total; "
              f"{j_calls} judge calls)")
        print(f"         cap_recall {micro_cap_r:.1%} is the CEILING the judge can "
              f"reach; recall_after_judge={judge_recall:.1%} is what it actually tags")
        # CAP CURVE from the single full-judged pass. For cap N: each doc's judged
        # slice = top-N RRF-ranked candidates; accept = score>=0.6; recall/precision
        # measured against the doc's exact truth_in_cat. One judged run answers
        # 15/20/30/50/uncapped — the tradeoff curve, no extra LLM cost.
        judged_docs = [d["judge"] for d in per_doc if d.get("judge")]
        print("\n  CAP CURVE (recall_after_judge / enh_recall / precision / avg calls/doc):")
        print(f"  {'cap':>6} {'recall':>8} {'enh_rec':>8} {'prec':>7} {'calls/doc':>10}")
        for capN in (15, 20, 30, 50, 9999):
            tt = at = aa = et = ea = calls = 0
            for jd in judged_docs:
                d_truth = set(jd["truth_in_cat"])
                scores = jd["scores"]
                topN = jd["ranked_all"][:capN]
                acc = {c for c in topN if scores.get(c, 0.0) >= T._LLM_TIER_ACCEPT_SCORE}
                acc_truth = acc & d_truth
                enh = {c for c in d_truth if _is_enhancement(c)}
                tt += len(d_truth); at += len(acc_truth); aa += len(acc)
                et += len(enh); ea += len(acc_truth & enh)
                calls += min(capN, len(jd["ranked_all"]))
            rec = at / tt if tt else 0.0
            enr = ea / et if et else 0.0
            prec = at / aa if aa else 0.0
            cd = calls / len(judged_docs) if judged_docs else 0.0
            print(f"  {('uncap' if capN==9999 else str(capN)):>6} "
                  f"{rec:8.1%} {enr:8.1%} {prec:7.1%} {cd:10.1f}")
    if truth_absent:
        n_absent = sum(len(v) for v in truth_absent.values())
        print(f"  NOTE   {n_absent} truth associations absent from current catalog "
              f"(excluded from recall): {truth_absent}")

    if args.json:
        Path(args.json).write_text(json.dumps({
            "meta": meta,
            "macro_gen_recall": macro_gen,
            "macro_cap_recall": macro_cap,
            "micro_gen_recall": micro_gen_r,
            "micro_cap_recall": micro_cap_r,
            "enh_gen_recall": enh_gen_r,
            "enh_cap_recall": enh_cap_r,
            "broad_gen_recall": broad_gen,
            "broad_cap_recall": broad_cap,
            "judge_precision": judge_precision,
            "judge_recall_after": judge_recall,
            "judge_calls": j_calls if args.with_judge else None,
            "micro_truth": micro_truth,
            "n": len(gen_r),
            "truth_absent_from_catalog": truth_absent,
            "per_doc": per_doc,
        }, indent=2))
        print(f"wrote {args.json}")
    if args.ledger:
        Path(args.ledger).write_text(json.dumps({
            "meta": meta, "docs": ledger_docs,
        }, indent=2))
        print(f"wrote ledger {args.ledger}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
