"""Alembic environment for cybersecurity-assessor.

Programmatic — no [alembic] sqlalchemy.url is set in alembic.ini. We resolve
the DB URL from ``config.db_path()`` so the migration tool always agrees with
the running sidecar about which sqlite file to operate on (per-user
``~/.cybersecurity-assessor/assessor.sqlite``), and tests can override the
target by passing ``connection`` directly via ``context.configure``.

Why ``render_as_batch=True``: SQLite's ALTER TABLE is famously limited —
no DROP COLUMN before 3.35, no MODIFY COLUMN ever, no ADD CONSTRAINT, no
REFERENCES on ADD COLUMN. Alembic's batch mode synthesizes the canonical
SQLite workaround (CREATE TABLE _new, INSERT … SELECT, DROP, RENAME) so
autogenerated diffs are actually applyable without hand-rewriting. The
130-entry ``_ADDITIVE_COLUMNS`` list in db.py exists precisely because the
prior implementation avoided that complexity; with batch mode we get the
full ALTER vocabulary at no extra cost.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel

# Importing the models package registers every table on SQLModel.metadata.
# Without this import, autogenerate would see an empty metadata and propose
# dropping all 55 tables on the next revision.
from cybersecurity_assessor import config as cfg
from cybersecurity_assessor import models  # noqa: F401 — side-effect import

# Alembic Config object provides access to alembic.ini values.
config = context.config

# Logging is configured from alembic.ini's [loggers] section.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# target_metadata drives autogenerate. SQLModel.metadata is the canonical
# source of truth for the application schema.
target_metadata = SQLModel.metadata


def _get_url() -> str:
    """Resolve the sqlite URL the live sidecar uses.

    ``CYBERSEC_ALEMBIC_URL`` overrides for dev/test scenarios — most often
    autogenerate runs (point at a scratch empty DB so the diff is
    metadata-vs-blank instead of metadata-vs-prod) and the equivalence test
    (points at an in-memory sqlite).
    """
    import os

    override = os.environ.get("CYBERSEC_ALEMBIC_URL")
    if override:
        return override
    return f"sqlite:///{cfg.db_path()}"


def run_migrations_offline() -> None:
    """Run migrations without a live DB connection (emits SQL to stdout)."""
    url = _get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live DB connection.

    If a caller (e.g. ``migrations.upgrade_to_head(engine)``) has already
    attached a connection to the config, reuse it — that lets the sidecar
    run upgrades over the same WAL-mode SQLAlchemy engine that serves the
    rest of the app, instead of opening a second connection that could race
    the pragma setup.
    """
    connectable = config.attributes.get("connection", None)

    if connectable is None:
        # CLI invocation path (``alembic upgrade head`` from a shell).
        # Build a connection on the fly using the resolved URL.
        ini_section = config.get_section(config.config_ini_section) or {}
        ini_section["sqlalchemy.url"] = _get_url()
        connectable = engine_from_config(
            ini_section,
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )
        with connectable.connect() as connection:
            _run_with_connection(connection)
    else:
        # Programmatic invocation from migrations.upgrade_to_head — the
        # caller owns connection lifecycle.
        _run_with_connection(connectable)


def _run_with_connection(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=True,
        # Compare server-default expressions when autogenerating so renames
        # of default constants don't slip through.
        compare_server_default=True,
        # Catch column type drift in autogenerate (e.g. String(64) vs
        # String(128)) — SQLite ignores most type lengths, but the diff is
        # informative for cross-engine portability later.
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
