"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-06 20:22:26.336444

The v0.x baseline. Captures the full ~55-table SQLModel state at the
moment we cut over from ad-hoc ``_ADDITIVE_COLUMNS`` migrations to
Alembic. Two pieces are NOT autogenerable and were added by hand at
the end of ``upgrade()``:

The two SystemContext partial unique indexes
(``ix_systemcontext_workbook_id_notnull`` and
``ix_systemcontext_pending_singleton``). SQLModel's class-level
``index=True`` cannot express the ``WHERE workbook_id IS [NOT] NULL``
predicates, so they previously lived in
``db._relax_systemcontext_sweeprun_workbook_id_nullability``. They
enforce the per-workbook 1:1 invariant AND the at-most-one
pending-row singleton. The seeded SweepWeights v1 row lives in
revision 0002 — schema migrations and data migrations stay in
separate files so the ``alembic upgrade`` graph is readable.

Prior dev/user databases that pre-date Alembic adoption must be wiped:
``db.init_db`` detects the missing ``alembic_version`` row and emits
the wipe-and-reseed instruction.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated migrations reference sqlmodel.* types


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crmanomalymodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('feature_schema_version', sa.Integer(), nullable=False),
    sa.Column('model_blob', sa.LargeBinary(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crmanomalymodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crmanomalymodel_feature_schema_version'), ['feature_schema_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmanomalymodel_is_active'), ['is_active'], unique=False)

    op.create_table('crmnarrativeembedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crmnarrativeembedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crmnarrativeembedding_narrative_sha256'), ['narrative_sha256'], unique=True)

    op.create_table('decisioncache',
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kernel_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    with op.batch_alter_table('decisioncache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisioncache_kernel_version'), ['kernel_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisioncache_prompt_sha'), ['prompt_sha'], unique=False)

    op.create_table('framework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('framework_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('oscal_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.Column('parent_framework_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('framework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_framework_id'), ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_parent_framework_id'), ['parent_framework_id'], unique=False)

    op.create_table('frameworkequivalence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_framework', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_odp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_framework', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_odp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frameworkequivalence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frameworkequivalence_source_framework'), ['source_framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_frameworkequivalence_source_odp_id'), ['source_odp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frameworkequivalence_target_framework'), ['target_framework'], unique=False)

    op.create_table('odpassignment',
    sa.Column('framework_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('odp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ingest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('oscal_param_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('framework_version', 'control_id', 'odp_id', 'assigned_from')
    )
    with op.batch_alter_table('odpassignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odpassignment_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odpassignment_framework_version'), ['framework_version'], unique=False)

    op.create_table('odpauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('odp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prev_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('who', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odpauditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odpauditlog_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odpauditlog_framework_version'), ['framework_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_odpauditlog_when'), ['when'], unique=False)

    op.create_table('promptsnapshot',
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    with op.batch_alter_table('promptsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promptsnapshot_prompt_kind'), ['prompt_kind'], unique=False)

    op.create_table('sweepweights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight_host', sa.Float(), nullable=False),
    sa.Column('weight_control_id', sa.Float(), nullable=False),
    sa.Column('weight_family', sa.Float(), nullable=False),
    sa.Column('weight_crm_keyword', sa.Float(), nullable=False),
    sa.Column('weight_doc_prefix', sa.Float(), nullable=False),
    sa.Column('weight_priority_link', sa.Float(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('surface_threshold', sa.Float(), nullable=False),
    sa.Column('precheck_threshold', sa.Float(), nullable=False),
    sa.Column('n_decisions_seen', sa.Integer(), nullable=False),
    sa.Column('auc', sa.Float(), nullable=True),
    sa.Column('parent_weights_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_weights_id'], ['sweepweights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sweepweights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sweepweights_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sweepweights_parent_weights_id'), ['parent_weights_id'], unique=False)

    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_name'), ['name'], unique=True)

    op.create_table('trustservicescriterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nist_800_53_refs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trustservicescriterion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trustservicescriterion_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_trustservicescriterion_criterion_id'), ['criterion_id'], unique=True)

    op.create_table('baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('CCIS_WORKBOOK', 'OSCAL_SSP', 'OSCAL_PROFILE', 'MANUAL', 'ISO_SOA', 'CIS_CSAT', 'CRM', 'PROGRAM_CONTROLS', 'OTHER', name='baselinesourcetype'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_framework_id'), ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baseline_system_id'), ['system_id'], unique=False)

    op.create_table('baselinemembership',
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('framework_id', 'control_id')
    )
    with op.batch_alter_table('baselinemembership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselinemembership_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselinemembership_framework_id'), ['framework_id'], unique=False)

    op.create_table('control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter_overrides_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_framework_id'), ['framework_id'], unique=False)

    op.create_table('engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_type', sa.Enum('SOC1_TYPE_1', 'SOC1_TYPE_2', 'SOC2_TYPE_1', 'SOC2_TYPE_2', 'SOC3', name='engagementtype'), nullable=False),
    sa.Column('service_org', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('auditor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_engagement_type'), ['engagement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_service_org'), ['service_org'], unique=False)

    op.create_table('requirementsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirementsource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirementsource_framework_id'), ['framework_id'], unique=False)

    op.create_table('baselinecontrol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('tailoring_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter_overrides_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsibility_narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsibility_onprem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsibility_onprem_narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baselinecontrol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselinecontrol_baseline_id'), ['baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselinecontrol_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselinecontrol_in_scope'), ['in_scope'], unique=False)

    op.create_table('controlcrosswalk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_control_id', sa.Integer(), nullable=False),
    sa.Column('to_control_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['from_control_id'], ['control.id'], ),
    sa.ForeignKeyConstraint(['to_control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controlcrosswalk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controlcrosswalk_from_control_id'), ['from_control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_controlcrosswalk_to_control_id'), ['to_control_id'], unique=False)

    op.create_table('controlobjective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('objective_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controlobjective', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controlobjective_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id_fk', sa.Integer(), nullable=False),
    sa.Column('objective_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('implementation_guidance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assessment_procedures', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['control_id_fk'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objective_control_id_fk'), ['control_id_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_objective_objective_id'), ['objective_id'], unique=False)

    op.create_table('workbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.Column('baseline_id', sa.Integer(), nullable=True),
    sa.Column('last_opened', sa.DateTime(), nullable=False),
    sa.Column('last_emass_import_at', sa.DateTime(), nullable=True),
    sa.Column('working_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sweep_attempts', sa.Integer(), nullable=False),
    sa.Column('total_sweep_cost_usd', sa.Float(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbook_baseline_id'), ['baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbook_path'), ['path'], unique=True)

    op.create_table('assessmentrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('validator_rejections', sa.Integer(), nullable=False),
    sa.Column('supersession_hits', sa.Integer(), nullable=False),
    sa.Column('ccis_accepted', sa.Integer(), nullable=False),
    sa.Column('abstained', sa.Integer(), nullable=False),
    sa.Column('dual_pass_disagreements', sa.Integer(), nullable=False),
    sa.Column('rewrites_requested', sa.Integer(), nullable=False),
    sa.Column('cache_hits', sa.Integer(), nullable=False),
    sa.Column('rule_8a_short_circuits', sa.Integer(), nullable=False),
    sa.Column('rule_8b_short_circuits', sa.Integer(), nullable=False),
    sa.Column('crm_short_circuit_count', sa.Integer(), nullable=False),
    sa.Column('validator_rejections_by_class', sa.JSON(), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_temperature', sa.Float(), nullable=True),
    sa.Column('system_prompt_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessmentrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmentrun_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fqdn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_class', sa.Enum('SERVER', 'WORKSTATION', 'NETWORK', 'APPLIANCE', 'CLOUD', 'OTHER', name='assetclass'), nullable=False),
    sa.Column('source', sa.Enum('SCAN', 'ASSET_LIST', 'MANUAL', name='assetsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_class'), ['asset_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('baselineobjective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('tailoring_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_row', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baselineobjective', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselineobjective_baseline_id'), ['baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselineobjective_is_deprecated'), ['is_deprecated'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselineobjective_objective_id'), ['objective_id'], unique=False)

    op.create_table('boundarysegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boundarysegment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boundarysegment_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_boundarysegment_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('TIER', 'SERVICE', 'SEGMENT', 'OTHER', name='componentkind'), nullable=False),
    sa.Column('parent_component_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_parent_component_id'), ['parent_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('crmcorpusfeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_baseline_id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('feature_schema_version', sa.Integer(), nullable=False),
    sa.Column('features_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crm_baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crmcorpusfeatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crmcorpusfeatures_crm_baseline_id'), ['crm_baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmcorpusfeatures_feature_schema_version'), ['feature_schema_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmcorpusfeatures_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('crmsuspicionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('crm_baseline_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('heuristic_score', sa.Float(), nullable=False),
    sa.Column('ml_anomaly_score', sa.Float(), nullable=True),
    sa.Column('narrative_quality_score', sa.Float(), nullable=True),
    sa.Column('overall_suspicion', sa.Float(), nullable=False),
    sa.Column('flags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_family_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_corpus', sa.Integer(), nullable=False),
    sa.Column('assessor_marked_false_positive', sa.Boolean(), nullable=True),
    sa.Column('assessor_review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['crm_baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crmsuspicionlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crmsuspicionlog_assessor_marked_false_positive'), ['assessor_marked_false_positive'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmsuspicionlog_crm_baseline_id'), ['crm_baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmsuspicionlog_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('crosswalk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_objective_id', sa.Integer(), nullable=False),
    sa.Column('to_objective_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['to_objective_id'], ['objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crosswalk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crosswalk_from_objective_id'), ['from_objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crosswalk_to_objective_id'), ['to_objective_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('PDF', 'DOCX', 'PPTX', 'XLSX', 'STIG_CKL', 'STIG_CKLB', 'STIG_XCCDF', 'NESSUS', 'TEXT', 'OTHER', name='evidencekind'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('extracted_text_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('archive_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superseded_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_asset_list', sa.Boolean(), nullable=False),
    sa.Column('asset_list_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('host_inventory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_boundary_doc', sa.Boolean(), nullable=False),
    sa.Column('boundary_doc_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_archive_uri'), ['archive_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_doc_number'), ['doc_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_is_asset_list'), ['is_asset_list'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_is_boundary_doc'), ['is_boundary_doc'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_path'), ['path'], unique=True)
        batch_op.create_index(batch_op.f('ix_evidence_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_kind'), ['source_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('poam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('control_cluster', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vulnerability_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('security_control_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emass_poam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_identifying_control_vulnerability', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('office_org', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ONGOING', 'RISK_ACCEPTED', 'COMPLETED', name='poamstatus'), nullable=False),
    sa.Column('scheduled_completion_date', sa.DateTime(), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(), nullable=True),
    sa.Column('likelihood', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel'), nullable=True),
    sa.Column('impact', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel'), nullable=True),
    sa.Column('raw_severity', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel'), nullable=True),
    sa.Column('relevance_of_threat', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel'), nullable=True),
    sa.Column('residual_risk', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel'), nullable=True),
    sa.Column('resources_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mitigations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('narrative_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poam_emass_poam_id'), ['emass_poam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poam_narrative_locked'), ['narrative_locked'], unique=False)
        batch_op.create_index(batch_op.f('ix_poam_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('requirementmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_source_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('requirement_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requirement_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['requirement_source_id'], ['requirementsource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirementmap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirementmap_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirementmap_requirement_source_id'), ['requirement_source_id'], unique=False)

    op.create_table('sweepdecision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('candidate_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_at_decision', sa.Float(), nullable=False),
    sa.Column('signals_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_ccis_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint_snapshot_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weights_version_id', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('auto_prechecked', sa.Boolean(), nullable=False),
    sa.Column('consumed_for_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weights_version_id'], ['sweepweights.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sweepdecision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sweepdecision_consumed_for_training'), ['consumed_for_training'], unique=False)
        batch_op.create_index(batch_op.f('ix_sweepdecision_weights_version_id'), ['weights_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sweepdecision_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('systemcontext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('FREEFORM_MARKDOWN', 'EMASS_SSP_XLSX', 'DOCX_NARRATIVE', 'OSCAL_SSP_JSON', name='systemcontextsourcetype'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('boundary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stakeholders', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tech_inventory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requirement_hints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_tokens', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('systemcontext', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_systemcontext_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('workbookoverlay',
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('attached_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('workbook_id', 'baseline_id')
    )
    op.create_table('workbooksyncevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cci_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbooksyncevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbooksyncevent_cci_id'), ['cci_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbooksyncevent_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbooksyncevent_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbooksyncevent_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbooksyncevent_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbooksyncevent_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('excel_row', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'NOT_APPLICABLE', name='compliancestatus'), nullable=False),
    sa.Column('tester', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_tested', sa.DateTime(), nullable=False),
    sa.Column('narrative_q', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('narrative_on_prem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative_cloud', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative_class', sa.Enum('COMPLIANCE_AFFIRMING', 'NA_JUSTIFYING', 'GAP_DESCRIBING', 'AMBIGUOUS', name='narrativeclass'), nullable=False),
    sa.Column('inheritance_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compensating_control', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rewrite_requested', sa.Boolean(), nullable=False),
    sa.Column('rewrite_requested_refs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verdict_source', sa.Enum('RULE_8A', 'RULE_8B', 'RULE_8C', 'RULE_NO_EVIDENCE', 'CRM_PROVIDER', 'CRM_INHERITED', 'CRM_NOT_APPLICABLE', 'CRM_HYBRID_MIXED', 'CACHE_HIT', 'LLM_ACCEPT', 'LLM_AFTER_RETRY', 'ABSTAIN', name='verdictsource'), nullable=True),
    sa.Column('dual_narrative_flagged', sa.Boolean(), nullable=False),
    sa.Column('dual_narrative_flag_reasons', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('written_to_workbook_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['assessmentrun.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_dual_narrative_flagged'), ['dual_narrative_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_rewrite_requested'), ['rewrite_requested'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_verdict_source'), ['verdict_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('calibrationentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('cci_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stated_confidence', sa.Float(), nullable=False),
    sa.Column('proposed_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('rewrite_requested', sa.Boolean(), nullable=False),
    sa.Column('human_accepted', sa.Boolean(), nullable=True),
    sa.Column('human_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessmentrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibrationentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibrationentry_cci_id'), ['cci_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibrationentry_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibrationentry_run_id'), ['run_id'], unique=False)

    op.create_table('componentasset',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'asset_id')
    )
    op.create_table('crmshortcircuitevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('control_id_fk', sa.Integer(), nullable=False),
    sa.Column('responsibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suspicion_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_id_fk'], ['control.id'], ),
    sa.ForeignKeyConstraint(['suspicion_log_id'], ['crmsuspicionlog.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crmshortcircuitevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crmshortcircuitevent_control_id_fk'), ['control_id_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmshortcircuitevent_suspicion_log_id'), ['suspicion_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crmshortcircuitevent_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('evidenceasset',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', 'BACKFILL', name='scopelinksource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'asset_id')
    )
    op.create_table('evidenceboundary',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('boundary_segment_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', 'BACKFILL', name='scopelinksource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boundary_segment_id'], ['boundarysegment.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'boundary_segment_id')
    )
    op.create_table('evidencecomponent',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', 'BACKFILL', name='scopelinksource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'component_id')
    )
    op.create_table('evidencetag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidencetag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidencetag_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencetag_framework_id'), ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencetag_objective_id'), ['objective_id'], unique=False)

    op.create_table('poamevidence',
    sa.Column('poam_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['poam_id'], ['poam.id'], ),
    sa.PrimaryKeyConstraint('poam_id', 'evidence_id')
    )
    op.create_table('poammilestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poam_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('changes_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poam_id'], ['poam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poammilestone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poammilestone_poam_id'), ['poam_id'], unique=False)

    op.create_table('poamobjective',
    sa.Column('poam_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('status_at_creation', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'NOT_APPLICABLE', name='compliancestatus'), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['poam_id'], ['poam.id'], ),
    sa.PrimaryKeyConstraint('poam_id', 'objective_id')
    )
    op.create_table('stigfinding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cci_refs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'NOT_A_FINDING', 'NOT_APPLICABLE', 'NOT_REVIEWED', name='findingstatus'), nullable=False),
    sa.Column('finding_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stigfinding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stigfinding_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stigfinding_rule_id'), ['rule_id'], unique=False)

    op.create_table('sweeprun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.Column('system_context_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('candidates_surfaced', sa.Integer(), nullable=False),
    sa.Column('candidates_judged', sa.Integer(), nullable=False),
    sa.Column('llm_cost_usd', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('judge_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weights_version_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_snapshot_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fallback_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['system_context_id'], ['systemcontext.id'], ),
    sa.ForeignKeyConstraint(['weights_version_id'], ['sweepweights.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sweeprun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sweeprun_system_context_id'), ['system_context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sweeprun_weights_version_id'), ['weights_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sweeprun_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('assessmentevidenceshown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('chunk_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('tag_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessmentevidenceshown', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmentevidenceshown_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessmentevidenceshown_chunk_sha'), ['chunk_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessmentevidenceshown_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('assessmenttrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anthropic_model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('pass_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['system_prompt_sha'], ['promptsnapshot.sha256'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessmenttrace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmenttrace_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('testofcontrol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('test_procedure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('deviation_rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testofcontrol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testofcontrol_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('assessmentcitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('narrative_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claim_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claim_start_char', sa.Integer(), nullable=True),
    sa.Column('claim_end_char', sa.Integer(), nullable=True),
    sa.Column('evidence_shown_id', sa.Integer(), nullable=False),
    sa.Column('source_quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_start_char', sa.Integer(), nullable=True),
    sa.Column('source_end_char', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['evidence_shown_id'], ['assessmentevidenceshown.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessmentcitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmentcitation_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessmentcitation_extraction_method'), ['extraction_method'], unique=False)

    # ### end Alembic commands ###

    # --- hand-added partial unique indexes ---------------------------------
    # SQLModel's index=True only emits a plain column index — these two
    # require a WHERE predicate (SQLite has supported partial indexes since
    # 3.8.0), so they have to be declared at the migration layer.
    #
    # 1) Per-workbook uniqueness for SystemContext: at most one row whose
    #    workbook_id matches a given workbook. NULL workbook_ids (the
    #    pre-workbook "pending" state) are excluded — they're governed by
    #    the second index below.
    op.execute(
        "CREATE UNIQUE INDEX ix_systemcontext_workbook_id_notnull "
        "ON systemcontext(workbook_id) WHERE workbook_id IS NOT NULL"
    )
    # 2) Pending-row singleton. SQLite treats NULLs as distinct in a UNIQUE
    #    index, so UNIQUE(workbook_id) WHERE workbook_id IS NULL would
    #    never collide. Indexing the constant expression `(1)` makes every
    #    matching row share the same key, so a second pending insert trips
    #    IntegrityError as the app code expects.
    op.execute(
        "CREATE UNIQUE INDEX ix_systemcontext_pending_singleton "
        "ON systemcontext((1)) WHERE workbook_id IS NULL"
    )


def downgrade() -> None:
    # Drop the hand-added partial indexes first — they reference systemcontext
    # which the autogenerated block tears down below.
    op.execute("DROP INDEX IF EXISTS ix_systemcontext_pending_singleton")
    op.execute("DROP INDEX IF EXISTS ix_systemcontext_workbook_id_notnull")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessmentcitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmentcitation_extraction_method'))
        batch_op.drop_index(batch_op.f('ix_assessmentcitation_assessment_id'))

    op.drop_table('assessmentcitation')
    with op.batch_alter_table('testofcontrol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testofcontrol_assessment_id'))

    op.drop_table('testofcontrol')
    with op.batch_alter_table('assessmenttrace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmenttrace_assessment_id'))

    op.drop_table('assessmenttrace')
    with op.batch_alter_table('assessmentevidenceshown', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmentevidenceshown_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_assessmentevidenceshown_chunk_sha'))
        batch_op.drop_index(batch_op.f('ix_assessmentevidenceshown_assessment_id'))

    op.drop_table('assessmentevidenceshown')
    with op.batch_alter_table('sweeprun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sweeprun_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_sweeprun_weights_version_id'))
        batch_op.drop_index(batch_op.f('ix_sweeprun_system_context_id'))

    op.drop_table('sweeprun')
    with op.batch_alter_table('stigfinding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stigfinding_rule_id'))
        batch_op.drop_index(batch_op.f('ix_stigfinding_evidence_id'))

    op.drop_table('stigfinding')
    op.drop_table('poamobjective')
    with op.batch_alter_table('poammilestone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poammilestone_poam_id'))

    op.drop_table('poammilestone')
    op.drop_table('poamevidence')
    with op.batch_alter_table('evidencetag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidencetag_objective_id'))
        batch_op.drop_index(batch_op.f('ix_evidencetag_framework_id'))
        batch_op.drop_index(batch_op.f('ix_evidencetag_evidence_id'))

    op.drop_table('evidencetag')
    op.drop_table('evidencecomponent')
    op.drop_table('evidenceboundary')
    op.drop_table('evidenceasset')
    with op.batch_alter_table('crmshortcircuitevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crmshortcircuitevent_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_crmshortcircuitevent_suspicion_log_id'))
        batch_op.drop_index(batch_op.f('ix_crmshortcircuitevent_control_id_fk'))

    op.drop_table('crmshortcircuitevent')
    op.drop_table('componentasset')
    with op.batch_alter_table('calibrationentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibrationentry_run_id'))
        batch_op.drop_index(batch_op.f('ix_calibrationentry_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_calibrationentry_cci_id'))

    op.drop_table('calibrationentry')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_verdict_source'))
        batch_op.drop_index(batch_op.f('ix_assessment_run_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_rewrite_requested'))
        batch_op.drop_index(batch_op.f('ix_assessment_objective_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_needs_review'))
        batch_op.drop_index(batch_op.f('ix_assessment_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_dual_narrative_flagged'))

    op.drop_table('assessment')
    with op.batch_alter_table('workbooksyncevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbooksyncevent_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_workbooksyncevent_source'))
        batch_op.drop_index(batch_op.f('ix_workbooksyncevent_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_workbooksyncevent_event_type'))
        batch_op.drop_index(batch_op.f('ix_workbooksyncevent_control_id'))
        batch_op.drop_index(batch_op.f('ix_workbooksyncevent_cci_id'))

    op.drop_table('workbooksyncevent')
    op.drop_table('workbookoverlay')
    with op.batch_alter_table('systemcontext', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_systemcontext_workbook_id'))

    op.drop_table('systemcontext')
    with op.batch_alter_table('sweepdecision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sweepdecision_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_sweepdecision_weights_version_id'))
        batch_op.drop_index(batch_op.f('ix_sweepdecision_consumed_for_training'))

    op.drop_table('sweepdecision')
    with op.batch_alter_table('requirementmap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirementmap_requirement_source_id'))
        batch_op.drop_index(batch_op.f('ix_requirementmap_objective_id'))

    op.drop_table('requirementmap')
    with op.batch_alter_table('poam', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poam_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_poam_narrative_locked'))
        batch_op.drop_index(batch_op.f('ix_poam_emass_poam_id'))

    op.drop_table('poam')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_superseded_by_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_source_kind'))
        batch_op.drop_index(batch_op.f('ix_evidence_sha256'))
        batch_op.drop_index(batch_op.f('ix_evidence_path'))
        batch_op.drop_index(batch_op.f('ix_evidence_is_boundary_doc'))
        batch_op.drop_index(batch_op.f('ix_evidence_is_asset_list'))
        batch_op.drop_index(batch_op.f('ix_evidence_doc_number'))
        batch_op.drop_index(batch_op.f('ix_evidence_archive_uri'))

    op.drop_table('evidence')
    with op.batch_alter_table('crosswalk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crosswalk_to_objective_id'))
        batch_op.drop_index(batch_op.f('ix_crosswalk_from_objective_id'))

    op.drop_table('crosswalk')
    with op.batch_alter_table('crmsuspicionlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crmsuspicionlog_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_crmsuspicionlog_crm_baseline_id'))
        batch_op.drop_index(batch_op.f('ix_crmsuspicionlog_assessor_marked_false_positive'))

    op.drop_table('crmsuspicionlog')
    with op.batch_alter_table('crmcorpusfeatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crmcorpusfeatures_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_crmcorpusfeatures_feature_schema_version'))
        batch_op.drop_index(batch_op.f('ix_crmcorpusfeatures_crm_baseline_id'))

    op.drop_table('crmcorpusfeatures')
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_component_parent_component_id'))
        batch_op.drop_index(batch_op.f('ix_component_name'))
        batch_op.drop_index(batch_op.f('ix_component_kind'))

    op.drop_table('component')
    with op.batch_alter_table('boundarysegment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boundarysegment_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_boundarysegment_name'))

    op.drop_table('boundarysegment')
    with op.batch_alter_table('baselineobjective', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselineobjective_objective_id'))
        batch_op.drop_index(batch_op.f('ix_baselineobjective_is_deprecated'))
        batch_op.drop_index(batch_op.f('ix_baselineobjective_baseline_id'))

    op.drop_table('baselineobjective')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_asset_source'))
        batch_op.drop_index(batch_op.f('ix_asset_hostname'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_class'))

    op.drop_table('asset')
    with op.batch_alter_table('assessmentrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmentrun_workbook_id'))

    op.drop_table('assessmentrun')
    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbook_path'))
        batch_op.drop_index(batch_op.f('ix_workbook_baseline_id'))

    op.drop_table('workbook')
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objective_objective_id'))
        batch_op.drop_index(batch_op.f('ix_objective_control_id_fk'))

    op.drop_table('objective')
    with op.batch_alter_table('controlobjective', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controlobjective_engagement_id'))

    op.drop_table('controlobjective')
    with op.batch_alter_table('controlcrosswalk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controlcrosswalk_to_control_id'))
        batch_op.drop_index(batch_op.f('ix_controlcrosswalk_from_control_id'))

    op.drop_table('controlcrosswalk')
    with op.batch_alter_table('baselinecontrol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselinecontrol_in_scope'))
        batch_op.drop_index(batch_op.f('ix_baselinecontrol_control_id'))
        batch_op.drop_index(batch_op.f('ix_baselinecontrol_baseline_id'))

    op.drop_table('baselinecontrol')
    with op.batch_alter_table('requirementsource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirementsource_framework_id'))

    op.drop_table('requirementsource')
    with op.batch_alter_table('engagement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_service_org'))
        batch_op.drop_index(batch_op.f('ix_engagement_engagement_type'))

    op.drop_table('engagement')
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_framework_id'))
        batch_op.drop_index(batch_op.f('ix_control_family'))
        batch_op.drop_index(batch_op.f('ix_control_control_id'))

    op.drop_table('control')
    with op.batch_alter_table('baselinemembership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselinemembership_framework_id'))
        batch_op.drop_index(batch_op.f('ix_baselinemembership_control_id'))

    op.drop_table('baselinemembership')
    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_system_id'))
        batch_op.drop_index(batch_op.f('ix_baseline_framework_id'))

    op.drop_table('baseline')
    with op.batch_alter_table('trustservicescriterion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trustservicescriterion_criterion_id'))
        batch_op.drop_index(batch_op.f('ix_trustservicescriterion_category'))

    op.drop_table('trustservicescriterion')
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_name'))

    op.drop_table('system')
    with op.batch_alter_table('sweepweights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sweepweights_parent_weights_id'))
        batch_op.drop_index(batch_op.f('ix_sweepweights_is_active'))

    op.drop_table('sweepweights')
    with op.batch_alter_table('promptsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promptsnapshot_prompt_kind'))

    op.drop_table('promptsnapshot')
    with op.batch_alter_table('odpauditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odpauditlog_when'))
        batch_op.drop_index(batch_op.f('ix_odpauditlog_framework_version'))
        batch_op.drop_index(batch_op.f('ix_odpauditlog_control_id'))

    op.drop_table('odpauditlog')
    with op.batch_alter_table('odpassignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odpassignment_framework_version'))
        batch_op.drop_index(batch_op.f('ix_odpassignment_control_id'))

    op.drop_table('odpassignment')
    with op.batch_alter_table('frameworkequivalence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frameworkequivalence_target_framework'))
        batch_op.drop_index(batch_op.f('ix_frameworkequivalence_source_odp_id'))
        batch_op.drop_index(batch_op.f('ix_frameworkequivalence_source_framework'))

    op.drop_table('frameworkequivalence')
    with op.batch_alter_table('framework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_parent_framework_id'))
        batch_op.drop_index(batch_op.f('ix_framework_name'))
        batch_op.drop_index(batch_op.f('ix_framework_framework_id'))

    op.drop_table('framework')
    with op.batch_alter_table('decisioncache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisioncache_prompt_sha'))
        batch_op.drop_index(batch_op.f('ix_decisioncache_kernel_version'))

    op.drop_table('decisioncache')
    with op.batch_alter_table('crmnarrativeembedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crmnarrativeembedding_narrative_sha256'))

    op.drop_table('crmnarrativeembedding')
    with op.batch_alter_table('crmanomalymodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crmanomalymodel_is_active'))
        batch_op.drop_index(batch_op.f('ix_crmanomalymodel_feature_schema_version'))

    op.drop_table('crmanomalymodel')
    # ### end Alembic commands ###
